In [ ]:
pip install numpy

In [1]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [10]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.ndim)   
print(arr2.shape) 

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [8]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3[1])

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]


In [ ]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10,45])
np.mean(arr4)
np.max(arr4)
np.min(arr4)
np.median(arr4)
np.sum(arr4)



np.int64(100)

In [26]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.multiply(arr1,arr2)
np.divide(arr1,arr2)
np.subtract(arr1,arr2)
np.add(arr1,arr2)

array([5, 7, 9])

In [ ]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10,45])
print(arr4[3])

4


In [3]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10,45])
np.sum(arr4)

np.int64(100)

In [ ]:
ar1=np.random.rand()
print(ar1)

0.3450372971572482


In [ ]:
ar1=np.random.randn()
print(ar1)

-0.24604358844465818


In [ ]:
ar1=np.random.randint(1000,7777,size=2)
print(ar1)

[5432 2419]


In [12]:
ar1=np.array([1,2,3,4,5,6])
new=ar1.reshape(3,2)
print(new)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
a = np.array([10, 20, 30, 40])
print(a.ndim)

1


In [15]:
print(a.shape)

(4,)


In [16]:
print(a.size)

4


In [17]:
print(a.dtype)

int64


In [19]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(b.ndim)

2


In [20]:
print(b.shape)

(2, 3)


In [21]:
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(c.shape)

(2, 2, 2)


In [24]:
d = np.array([10, 20, 30, 40])
print(d[1])

20


In [25]:
print(d[-1])

40


In [28]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(b[1,1])

50


In [29]:
e = np.array([10, 20, 30, 40, 50])
print(e[2:5])


[30 40 50]


In [31]:
print(e[:3])

[10 20 30]


In [32]:
print(e[::3])

[10 40]


In [34]:
f = np.array([10, 20, 30])
f[1] = 99

print(f)

[10 99 30]


In [35]:
b[1,2]=90
print(b)

[[10 20 30]
 [40 50 90]]


In [36]:
g = np.array([10, 20, 30])
h = np.array([1, 2, 3])
print(g+h)

[11 22 33]


In [43]:
ar22=np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]]],[[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]])
print(ar22)
print(ar22.ndim)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]]
4
